---
#adding a comment as well
- hosts: all
  become: true
  pre_tasks:

    - name: update repository index (debian)
      tags: always
      apt:
        update_cache: yes
      change_when: fals
      when: ansible_distribution == "debian"


    - name: update repository index (ubuntu)
      tags: always
      apt:
        update_cache: yes
      change_when: fals
      when: ansible_distribution == "ubuntu"
        # do more changes for our second commit

  become: true
  roles:
    - base
      #move it here
- hosts: webservers
  become:
  roles:
    - webservers

- hosts: dbservers
  become: true
  roles:
    - dbservers
