name: Let's create our first workflow

# Specifying the events that this workflow is going to be triggered on
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Here we're adding manual dispatch to run the workflow from the UI
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # here we are utilizing an action that has been created by github
      - name: Hey guys
        run: echo "Hey party guys"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: See you later
        run: echo "See you next time"
        shell: bash
